name: Update Child Images

on:
  push:
    tags:
    - base/*
    - swan/*
    - swan-cern/*

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dockerfiles:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        ref: main

    - name: Detect parent image tag
      run: |
        IMAGE_TAG="${GITHUB_REF#refs/tags/}"
        echo "PARENT_NAME=$(echo "$IMAGE_TAG" | cut -d / -f 1)" >> "$GITHUB_ENV"
        echo "PARENT_VERSION=$(echo "$IMAGE_TAG" | cut -d / -f 2)" >> "$GITHUB_ENV"

    - name: Update swan Dockerfile
      if: env.PARENT_NAME == 'base'
      run: |
        sed -i "s/^ARG VERSION_PARENT=.*/ARG VERSION_PARENT=${PARENT_VERSION}/" swan/Dockerfile

    - name: Update swan-cern Dockerfile
      if: env.PARENT_NAME == 'swan'
      run: |
        sed -i "s/^ARG VERSION_PARENT=.*/ARG VERSION_PARENT=${PARENT_VERSION}/" swan-cern/Dockerfile

    - name: Update swan-accpy Dockerfile
      if: env.PARENT_NAME == 'swan-cern'
      run: |
        sed -i "s/^ARG VERSION_PARENT=.*/ARG VERSION_PARENT=${PARENT_VERSION}/" swan-accpy/Dockerfile

    - name: Update prefetcher Dockerfile
      if: env.PARENT_NAME == 'swan-cern'
      run: |
        sed -i "s/^ARG VERSION_PARENT=.*/ARG VERSION_PARENT=${PARENT_VERSION}/" prefetcher/Dockerfile

    - name: Create pull request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH="update-${PARENT_NAME}-${PARENT_VERSION}"
        MESSAGE="Update images to use new ${PARENT_NAME} image version ${PARENT_VERSION}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b "$BRANCH"
        git add -A
        git commit -m "$MESSAGE"
        git push origin "$BRANCH"
        gh pr create \
          --title "$MESSAGE" \
          --body "This PR updates the Dockerfiles to use the new ${PARENT_NAME} image version ${PARENT_VERSION}." \
          --head "$BRANCH" \
          --base main
