name: Release
run-name: Release ${{ inputs.image }} (and dependents) by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image to release"
        required: true
        type: choice
        options:
          - base
          - swan
          - swan-cern
          - swan-accpy
          - prefetcher

# Dependency tree:
#   base → swan → swan-cern → swan-accpy
#                           → prefetcher

jobs:
  release-base:
    if: inputs.image == 'base'
    uses: ./.github/workflows/_release-image.yml
    with:
      image: base
      children: swan
    secrets: inherit

  release-swan:
    if: >-
      !failure() && !cancelled() &&
      contains(fromJSON('["base", "swan"]'), inputs.image)
    needs: release-base
    uses: ./.github/workflows/_release-image.yml
    with:
      image: swan
      children: swan-cern
      notify-swan-charts: true
    secrets: inherit

  release-swan-cern:
    if: >-
      !failure() && !cancelled() &&
      contains(fromJSON('["base", "swan", "swan-cern"]'), inputs.image)
    needs: release-swan
    uses: ./.github/workflows/_release-image.yml
    with:
      image: swan-cern
      children: "swan-accpy prefetcher"
      notify-swan-charts: true
    secrets: inherit

  release-swan-accpy:
    if: >-
      !failure() && !cancelled() &&
      contains(fromJSON('["base", "swan", "swan-cern", "swan-accpy"]'), inputs.image)
    needs: release-swan-cern
    uses: ./.github/workflows/_release-image.yml
    with:
      image: swan-accpy
      notify-swan-charts: true
    secrets: inherit

  release-prefetcher:
    if: >-
      !failure() && !cancelled() &&
      contains(fromJSON('["base", "swan", "swan-cern", "prefetcher"]'), inputs.image)
    needs: release-swan-cern
    uses: ./.github/workflows/_release-image.yml
    with:
      image: prefetcher
    secrets: inherit
