name: Bump version of swan-cern in other repositories

on:
  push:
    tags:
    - swan-cern/*

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set environnment package name  and version
      run: |
        IMAGE_TAG=${GITHUB_REF#refs/tags/}
        echo "IMAGE_NAME=$(echo $IMAGE_TAG | cut -d / -f 1)" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$(echo $IMAGE_TAG | cut -d / -f 2)" >> $GITHUB_ENV
    
    - name: Invoke workflow in swan-charts
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Update jupyter and jupyterhub images
        ref: master
        repo: swan-cern/swan-charts
        token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
        inputs: '{ "image": "${{env.IMAGE_NAME}}", "version": "${{env.IMAGE_VERSION}}" }'