name: Bump jupyter images versions in swan-charts

on:
  push:
    tags:
    - swan/*
    - swan-cern/*
    - swan-accpy/*

jobs:
  notify-swan-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger image version update in swan-charts
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
      run: |
        IMAGE_TAG="${GITHUB_REF#refs/tags/}"
        IMAGE_NAME="jupyter/$(echo "$IMAGE_TAG" | cut -d / -f 1)"
        IMAGE_VERSION="$(echo "$IMAGE_TAG" | cut -d / -f 2)"

        gh workflow run "Update jupyter and jupyterhub images" \
          --repo swan-cern/swan-charts \
          --ref master \
          -f image="$IMAGE_NAME" \
          -f version="$IMAGE_VERSION"
